### ISSUE TITLE
issue when logged in with Theatre mode on

### ISSUE THREAD

**Issue by TwitchKappa** [chylex/Transparent-Twitch-Chat#4]
When the user is logged in to the twitch website and viewing a stream, and Theatre mode is enabled, and the user clicks on the upper right button to show or hide the chat, a bug occurs when the chat is hidden. When the chat is hidden the player does not take up as much of the screen as it can and there are black bars on the sides and bottom of the page.

This only happens when the user is logged in, if the user is not logged in this bug does not occur. Theatre mode must also be enabled and chat must be hidden by using the button in the upper right corner.

This issue affects your add-on because it works in Theatre mode. I have contacted twitch support and they claim that is intended  so you will need to find a workaround. Thank you.

**Comment by TwitchKappa** [comment]
![waterfox_2017-06-26_19-58-48](https://user-images.githubusercontent.com/23336873/30224794-1a9b165e-949e-11e7-8608-2baa1b85698e.jpg)

**Comment by chylex** [comment]
I'll look into it and release an update tomorrow, just noting a couple observations so I don't forget:

```css
.app-main.theatre .conversations-wrapper { background: none }
.app-main.theatre .player-whispers-padding { margin-bottom: 0 !important }
```
